[workspace]

members = [
	"binary_tree",
	"builder_type", 
	"collatz",
	"counter",
	"elevator_event",
	"expression_evaluation",
	"fibonnaci",
	"geometry",
	"generic_min",
	"gui_lib",
	"nested_arrays",
]
